### ISSUE TITLE
Google Drive Migration: Drive Audit

### ISSUE THREAD

**Issue by BCHEN222** [hackforla/google-drive-migration#3]
### Overview
Epic for tracking the progress of a specific team for their drive migration
### Action Items
- [x] Setup email address drivemigration@hackforla.org
  - [x] Setup in Gsuite
  - [x] Setup in 1Password
    - [x] Add team members to 1password
- [x] setup Google Drive Migration Shared Drive
  - [x] add team members and drivemigration@ to drive
- [x] Setup repo team
  - [x] add team members
- [x] Create tracking spreadsheet in drive migration google
   - [x] Add list of projects to sheet
- [x] Give permission for drives old and new to drivemigration@
- [x] create a template issue
   - [x] create issues for each project

### Resources/Instructions
- [google drive migration github team](https://github.com/orgs/hackforla/teams/google-drive-migration/members)
- https://github.com/hackforla/product-management/issues/321
- [Active Project List Spreadsheet](https://docs.google.com/spreadsheets/d/1S_g8fHmRhSIXI_VJMVDNdVg1XtN06QoTZtPC1O0GNnw/edit#gid=0)
- [HfLA old drive structure](https://drive.google.com/drive/u/0/folders/1mRmBMk6nEvylSOiC7l__XCx5qU3g9w-B)
- [Drive audit issue template](https://github.com/hackforla/google-drive-migration/issues/new?assignees=&labels=&template=drive-audit-issue-template.md&title=Drive+Audit%3A+%5BProject+Name%5D)
- [Template for Drive Audit](https://docs.google.com/spreadsheets/d/1uw3SJHe2MOHGaCwbxnanLfqPvggGvLMqBAQloJBNirE/copy)

#### Team members
- Bonnie, Executive Director, Hack for LA
- Charity, Project Management Intern 2022
- Brian, Project Management Intern 2022

#### All Audit issues created for projects and CoPs
- [feature: project audit](https://github.com/hackforla/google-drive-migration/issues?q=is%3Aissue+label%3A%22feature%3A+project+audit%22)

**Comment by BCHEN222** [comment]
ACTION ITEM: 

- [ ] When Drive Migration is completed in whole, check off "drive migration completed" in [Active Project List Spreadsheet (https://docs.google.com/spreadsheets/d/1S_g8fHmRhSIXI_VJMVDNdVg1XtN06QoTZtPC1O0GNnw/edit#gid=0)

**Comment by BCHEN222** [comment]
List of PMs at CoP meeting Friday 6/24

AJ - Access the Data
Ben - Home Unite US
Rabia, Priyanka - Internship
James - Expunge Assist 
Henry - 100 Automations
Stacey - BallotNav
Bonnie - Website team, guides team, GreenEarthOS

**Comment by BCHEN222** [comment]
Hi everybody- please make sure that you are **moving the original files** from the old drive to the new one. Please note to **not make duplicates** of the files, and that you **must** move the original ones. This is because when we delete legacy content, the links we have to those files will be destroyed. 

For example, - https://github.com/hackforla/expunge-assist/issues/11  has links to several files. This is an old issue and has since been closed, but if these files were needed for reference in the future, the links would be destroyed if the files were duplicated, not moved. There are countless issues like that one with old files that are still important and will be referenced again. Thus, it is **imperative** that legacy content be migrated from old to new drives, not duplicated, such that we maintain the integrity and ease of access to legacy content. We appreciate your hard work and cooperation.

**Comment by ExperimentsInHonesty** [comment]
issues need to be updated by adding

```
   - [ ] get files moved
   - [ ] Once files moved, add label to issue `status: ready for final review`
- [ ] Confirm old drive is empty
- [ ] check off "drive migration completed" in [Active Project List Spreadsheet](https://docs.google.com/spreadsheets/d/1S_g8fHmRhSIXI_VJMVDNdVg1XtN06QoTZtPC1O0GNnw/edit#gid=0)

```

see this issue as example

**Comment by Rabia2219** [comment]
Steps:
- log into drive migration account using 1password
- log into personal GitHub account in drive migration profile
  - will need GitHub handle and password

**Comment by ExperimentsInHonesty** [comment]
#61 has a new template in it
