### ISSUE TITLE
GDM: Agenda Product-Management Meeting

### ISSUE THREAD

**Issue by CharityLai6** [hackforla/google-drive-migration#7]
### Overview
This issue tracks the agenda for our weekly meetings

#### Issue Template
```
## [Date ]  Meeting Agenda

### Prework to prep for meeting
- [ ] #

### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Name of Person]
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
```

### Links to other agenda issues for your team 
(so that you can easily post on their agendas items that come up at yours)

**Comment by CharityLai6** [comment]
## 2022-06-24  Meeting Agenda


### Recurring items: Happens on the Friday meeting
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Name of Person]
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
